### ISSUE TITLE
Server fail to start when history directory is removed

### ISSUE THREAD

**Issue by ppolakiewicz** [devdo-eu/capturenetwork#37]
History directory is quite important for our server.
If it's removed then server fail to start cause there will be FileNotFound error on line
https://github.com/devdo-eu/capturenetwork/blob/6af5ffd7aef69965db523eb64efc1c8292a34f85/dispatcher.py#L80

Please add validation if this path exists before opening file and create it if it's lost.

**Comment by devdo-eu** [comment]
Hmm... But You know that `.\history` directory is part of repository?
If You delete any other folder from repository, start of server execution **should** end immediately with exception.

Inside `.\history\games` is **insight.ipynb** file which is tracked in repo.

But when there is a need to erase all history it is easy to just delete `./history` folder - just like You did. 
I will fix this bug.
